name: Build and deploy Next.js app to Azure Web App - SweatSmartly

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Zorg dat dit overeenkomt met Azure Node versie

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js standalone output
        run: npm run build

      - name: Copy files for Azure deployment
        run: |
          mkdir -p deploy
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static || echo "Geen static folder gevonden"
          cp -r public/ deploy/public
          cp next.config.mjs deploy/
          cp package.json deploy/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SweatSmartly'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./deploy
