name: Build, Test and Deploy Next.js App - SweatSmartly

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Jest unit/component tests
      - name: Run Jest tests
        run: npm run test

      # 5. Build Next.js production build
      - name: Build Next.js app
        env:
          NODE_ENV: production
        run: npm run build

      # 6. Run Cypress E2E tests
      - name: Run Cypress E2E tests
        run: npm run cy:run

      # 7. Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: |
            .next
            public
            package.json
            next.config.js

      # 8. Download build artifact (for deployment)
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build

      # 9. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SweatSmartly'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
